# Generated by Django 3.0.8 on 2020-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='categoryz',
            field=models.CharField(default='Uncategorised', max_length=100),
        ),
    ]
