# Generated by Django 3.0.8 on 2020-07-18 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='categoryz',
        ),
        migrations.AlterField(
            model_name='tag',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
