# Generated by Django 3.0.8 on 2020-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20200718_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='snippet',
            field=models.CharField(default='Click above link to view the post', max_length=1000),
        ),
    ]
