# Generated by Django 3.0.8 on 2020-08-03 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
        migrations.CreateModel(
            name='stall_frames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('cover', models.ImageField(default='', upload_to='coverimages')),
                ('description', models.CharField(default='', max_length=300)),
                ('contact_stall', models.CharField(default='', max_length=300)),
                ('premium', models.BooleanField(default=False)),
                ('stall_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stall_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='products_images')),
                ('stall_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.stall_frames')),
            ],
        ),
    ]
